baseURL = "https://marcdicarlo.github.io/midtech-blog/" # Must end with splash
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

canonifyURLs = true
staticDir = ["themes/Niello/static", "static"]

theme = "Niello"

[languages]
	[languages.en]
		title = "{CodeTrace} - Discover Issues, Share Solutions."
		languageCode = "en-us"
		LanguageName = "🇺🇸EN"
		contentDir = "content/en"
		weight = 1
		[[languages.en.menus.main]]
			name = 'Home'
			pageRef = '/'
			weight = 1
		[[languages.en.menus.main]]
			name = 'Categories'
			pageRef = '/categories'
			weight = 2
		[[languages.en.menus.main]]
			name = 'Tags'
			pageRef = '/tags'
			weight = 3
		[[languages.en.menus.main]]
			name = 'Contact'
			pageRef = '/contact'
			weight = 4

        
[params]

[params.google]

[params.bannershowcase]
	categories = ["AI", "FOO", "BAR"]
	limit = 2
[params.email]
	contact = "info@midtech.dev"
[params.ignore]
	categories = ["privacy", "terms", "archives", "cookie"]
[params.license]
	copyright = "&#xA9; 2025 by midtech.dev. All Rights Reserved."
[params.share]
[params.disqus]

[outputs]
  home = ["HTML", "JSON"]
    